spring:
  application:
    name: product-server
  data:
    mongodb:
      username: root
      password: root
      database: productdb
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080
